import { site } from '@/data/site'
import { usePageMeta } from '@/lib/usePageMeta'
import { Callout } from '@/components/ui/Callout'
import { Container } from '@/components/ui/Container'
import { Prose, ProseList, ProseSection } from '@/components/ui/Prose'
import { Section } from '@/components/ui/Section'
import { DarkPageHero } from '@/components/sections/DarkPageHero'

const LAST_UPDATED = 'September 2026'

export default function Privacy() {
  usePageMeta({
    title: 'Privacy Policy | How Skyward Invexa Handles Your Data',
    description:
      'How Skyward Invexa collects, uses, stores and discloses personal information, and how to access or correct the information we hold about you.',
    path: '/privacy',
  })

  return (
    <>
      <DarkPageHero
        eyebrow={`Last updated ${LAST_UPDATED}`}
        title="Skyward Invexa Privacy Policy"
        lead={`How ${site.name} handles personal information collected through ${site.domain} and through your account.`}
      />

      <Section>
        <Container>
          <Callout tone="warn" title="Before This Page Goes Live" className="mb-12 max-w-3xl">
            This policy is a working draft written to match how the site actually behaves. It must be
            reviewed by a qualified Australian privacy lawyer against the Privacy Act 1988 (Cth) and
            the Australian Privacy Principles, and the placeholders below replaced with real details,
            before the site is published.
          </Callout>

          <Prose>
            <ProseSection heading="1. What This Policy Covers">
              <p>
                This policy explains what personal information we collect, why we collect it, how we
                store and use it, who we share it with, and how you can access or correct it. It
                applies to this website and to any account you hold with us.
              </p>
              <p>
                We are bound by the Privacy Act 1988 (Cth) and the Australian Privacy Principles.
                Where the General Data Protection Regulation applies to a visitor, we also handle
                that visitor&apos;s information in line with it.
              </p>
            </ProseSection>

            <ProseSection heading="2. Information We Collect">
              <p>We collect information in three ways.</p>
              <ProseList
                items={[
                  'Information you provide directly: name, email address, phone number, date of birth, residential address and the contents of any message you send us.',
                  'Identity verification information: documents and data supplied by you or returned by an identity verification provider when you open an account, as required by Australian anti-money laundering obligations.',
                  'Information generated by your use of the site: pages viewed, approximate location derived from IP address, browser and device type, and timestamps of visits.',
                ]}
              />
            </ProseSection>

            <ProseSection heading="3. Why We Collect It">
              <ProseList
                items={[
                  'To verify your identity and assess suitability, as required before an account can be opened.',
                  'To operate your account: processing orders, deposits, withdrawals and statements.',
                  'To respond to enquiries you send through the contact form or by email.',
                  'To meet legal obligations, including anti-money laundering, counter-terrorism financing, tax reporting and record-keeping requirements.',
                  'To detect and prevent fraud, unauthorised access and misuse of the platform.',
                ]}
              />
              <p>
                We do not sell personal information, and we do not use it to build advertising
                profiles of you across other websites.
              </p>
            </ProseSection>

            <ProseSection heading="4. Who We Share It With">
              <p>
                We share personal information only where it is necessary, and only with parties
                bound by confidentiality and privacy obligations:
              </p>
              <ProseList
                items={[
                  'Identity verification and anti-money-laundering service providers.',
                  'Market counterparties, custodians and settlement providers, to the extent required to execute and settle your instructions.',
                  'Banking and payment providers, to process transfers you initiate.',
                  'Professional advisers, auditors and insurers, where required.',
                  'Government agencies and regulators, where we are legally compelled to disclose.',
                ]}
              />
              <p>
                Where a provider stores or processes information outside Australia, we remain
                responsible for that information and take reasonable steps to ensure it is handled to
                a comparable standard.
              </p>
            </ProseSection>

            <ProseSection heading="5. Cookies and Analytics">
              <p>
                This site uses cookies that are necessary for it to function, such as remembering
                whether the navigation menu is open. If we add analytics or advertising cookies, we
                will list them here and ask for your consent where consent is required before they
                are set.
              </p>
            </ProseSection>

            <ProseSection heading="6. How Long We Keep It">
              <p>
                Account records are retained for the period required by Australian record-keeping
                obligations after your account is closed, which is generally seven years. Enquiries
                made through the contact form that do not become an account are kept for two years
                and then deleted.
              </p>
            </ProseSection>

            <ProseSection heading="7. Security">
              <p>
                Information is encrypted in transit and at rest. Access to production systems is
                role-based, logged, and limited to staff who need it to perform their role. Where we
                become aware of a data breach that is likely to result in serious harm, we will
                notify affected individuals and the Office of the Australian Information
                Commissioner as required by the Notifiable Data Breaches scheme.
              </p>
            </ProseSection>

            <ProseSection heading="8. Access, Correction and Complaints">
              <p>
                You can request access to the personal information we hold about you, ask us to
                correct it, or ask us to delete it where we are not required to retain it. Contact us
                at{' '}
                <a
                  href={`mailto:${site.emails.compliance}`}
                  className="text-brand-600 hover:text-brand-700"
                >
                  {site.emails.compliance}
                </a>
                . We will respond within 30 days.
              </p>
              <p>
                If you are not satisfied with our response, you may complain to the Office of the
                Australian Information Commissioner at oaic.gov.au.
              </p>
            </ProseSection>

            <ProseSection heading="9. Changes to This Policy">
              <p>
                We will update this page when our practices change and revise the date at the top.
                Material changes affecting account holders are notified by email before they take
                effect.
              </p>
            </ProseSection>
          </Prose>
        </Container>
      </Section>
    </>
  )
}
